<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.cQeGiWP' shared service.

return $this->privates['.service_locator.cQeGiWP'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('user1Repository' => function (): \App\Repository\User1Repository {
    return ($this->privates['App\Repository\User1Repository'] ?? $this->load('getUser1RepositoryService.php'));
}));
