<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGBl9Ofc\srcEnvDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGBl9Ofc/srcEnvDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerGBl9Ofc.legacy');

    return;
}

if (!\class_exists(srcEnvDebugProjectContainer::class, false)) {
    \class_alias(\ContainerGBl9Ofc\srcEnvDebugProjectContainer::class, srcEnvDebugProjectContainer::class, false);
}

return new \ContainerGBl9Ofc\srcEnvDebugProjectContainer(array(
    'container.build_hash' => 'GBl9Ofc',
    'container.build_id' => 'c0f9939b',
    'container.build_time' => 1541113146,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerGBl9Ofc');
