<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT9S2fq4\srcEnvDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT9S2fq4/srcEnvDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerT9S2fq4.legacy');

    return;
}

if (!\class_exists(srcEnvDebugProjectContainer::class, false)) {
    \class_alias(\ContainerT9S2fq4\srcEnvDebugProjectContainer::class, srcEnvDebugProjectContainer::class, false);
}

return new \ContainerT9S2fq4\srcEnvDebugProjectContainer(array(
    'container.build_hash' => 'T9S2fq4',
    'container.build_id' => 'f437a674',
    'container.build_time' => 1541425201,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerT9S2fq4');
