<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.YU.8.TJ.App\Entity\Facturas' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.YU.8.TJ": it references class "App\\Entity\\Facturas" but no such service exists.');
