<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.yfKiB9f' shared service.

return $this->privates['.service_locator.yfKiB9f'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('proveedoresRepository' => function (): \App\Repository\ProveedoresRepository {
    return ($this->privates['App\Repository\ProveedoresRepository'] ?? $this->load('getProveedoresRepositoryService.php'));
}));
