<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.9Dq1.6i.App\Entity\Ingresos' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.9Dq1.6i": it references class "App\\Entity\\Ingresos" but no such service exists.');
