<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.MpabvJx.App\Entity\Productos' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.MpabvJx": it references class "App\\Entity\\Productos" but no such service exists.');
