<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'pugx_autocompleter.autocomplete' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\FormTypeInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\AbstractType.php';
include_once $this->targetDirs[3].'\\vendor\\pugx\\autocompleter-bundle\\src\\Form\\Type\\AutocompleteType.php';

return $this->services['pugx_autocompleter.autocomplete'] = new \PUGX\AutocompleterBundle\Form\Type\AutocompleteType(($this->services['doctrine'] ?? $this->getDoctrineService()));
