<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUaYJfNb\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUaYJfNb/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerUaYJfNb.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerUaYJfNb\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerUaYJfNb\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'UaYJfNb',
    'container.build_id' => '3818c5f6',
    'container.build_time' => 1541550933,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerUaYJfNb');
