<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXkjxqme\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXkjxqme/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerXkjxqme.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerXkjxqme\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerXkjxqme\srcProdProjectContainer(array(
    'container.build_hash' => 'Xkjxqme',
    'container.build_id' => '1dccfc0a',
    'container.build_time' => 1542820450,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXkjxqme');
