<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKLdaFAr\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKLdaFAr/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerKLdaFAr.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerKLdaFAr\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerKLdaFAr\srcProdProjectContainer(array(
    'container.build_hash' => 'KLdaFAr',
    'container.build_id' => 'a47b797b',
    'container.build_time' => 1541208008,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerKLdaFAr');
