<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGzbizeM\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGzbizeM/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerGzbizeM.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerGzbizeM\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerGzbizeM\srcProdProjectContainer(array(
    'container.build_hash' => 'GzbizeM',
    'container.build_id' => '449055df',
    'container.build_time' => 1540709384,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerGzbizeM');
