<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Clientes extends \App\Entity\Clientes implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Clientes' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Clientes' . "\0" . 'nombre', '' . "\0" . 'App\\Entity\\Clientes' . "\0" . 'nit', '' . "\0" . 'App\\Entity\\Clientes' . "\0" . 'IdUsuario', '' . "\0" . 'App\\Entity\\Clientes' . "\0" . 'contactoPrincipal', '' . "\0" . 'App\\Entity\\Clientes' . "\0" . 'correo', '' . "\0" . 'App\\Entity\\Clientes' . "\0" . 'fechaNacimiento', '' . "\0" . 'App\\Entity\\Clientes' . "\0" . 'comentarios', '' . "\0" . 'App\\Entity\\Clientes' . "\0" . 'zona', '' . "\0" . 'App\\Entity\\Clientes' . "\0" . 'dpto', '' . "\0" . 'App\\Entity\\Clientes' . "\0" . 'municipio', '' . "\0" . 'App\\Entity\\Clientes' . "\0" . 'telefonoMovil', '' . "\0" . 'App\\Entity\\Clientes' . "\0" . 'telefonoLocal', '' . "\0" . 'App\\Entity\\Clientes' . "\0" . 'direccion', '' . "\0" . 'App\\Entity\\Clientes' . "\0" . 'facturas'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Clientes' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Clientes' . "\0" . 'nombre', '' . "\0" . 'App\\Entity\\Clientes' . "\0" . 'nit', '' . "\0" . 'App\\Entity\\Clientes' . "\0" . 'IdUsuario', '' . "\0" . 'App\\Entity\\Clientes' . "\0" . 'contactoPrincipal', '' . "\0" . 'App\\Entity\\Clientes' . "\0" . 'correo', '' . "\0" . 'App\\Entity\\Clientes' . "\0" . 'fechaNacimiento', '' . "\0" . 'App\\Entity\\Clientes' . "\0" . 'comentarios', '' . "\0" . 'App\\Entity\\Clientes' . "\0" . 'zona', '' . "\0" . 'App\\Entity\\Clientes' . "\0" . 'dpto', '' . "\0" . 'App\\Entity\\Clientes' . "\0" . 'municipio', '' . "\0" . 'App\\Entity\\Clientes' . "\0" . 'telefonoMovil', '' . "\0" . 'App\\Entity\\Clientes' . "\0" . 'telefonoLocal', '' . "\0" . 'App\\Entity\\Clientes' . "\0" . 'direccion', '' . "\0" . 'App\\Entity\\Clientes' . "\0" . 'facturas'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Clientes $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre(string $nombre): \App\Entity\Clientes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNit(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNit', []);

        return parent::getNit();
    }

    /**
     * {@inheritDoc}
     */
    public function setNit(string $nit): \App\Entity\Clientes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNit', [$nit]);

        return parent::setNit($nit);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUsuario(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUsuario', []);

        return parent::getIdUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUsuario(?\App\Entity\User $IdUsuario): \App\Entity\Clientes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUsuario', [$IdUsuario]);

        return parent::setIdUsuario($IdUsuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactoPrincipal(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactoPrincipal', []);

        return parent::getContactoPrincipal();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactoPrincipal(string $contactoPrincipal): \App\Entity\Clientes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactoPrincipal', [$contactoPrincipal]);

        return parent::setContactoPrincipal($contactoPrincipal);
    }

    /**
     * {@inheritDoc}
     */
    public function getCorreo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCorreo', []);

        return parent::getCorreo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCorreo(string $correo): \App\Entity\Clientes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCorreo', [$correo]);

        return parent::setCorreo($correo);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaNacimiento(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaNacimiento', []);

        return parent::getFechaNacimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaNacimiento(\DateTimeInterface $fechaNacimiento): \App\Entity\Clientes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaNacimiento', [$fechaNacimiento]);

        return parent::setFechaNacimiento($fechaNacimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getComentarios(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComentarios', []);

        return parent::getComentarios();
    }

    /**
     * {@inheritDoc}
     */
    public function setComentarios(string $comentarios): \App\Entity\Clientes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComentarios', [$comentarios]);

        return parent::setComentarios($comentarios);
    }

    /**
     * {@inheritDoc}
     */
    public function getZona(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZona', []);

        return parent::getZona();
    }

    /**
     * {@inheritDoc}
     */
    public function setZona(string $zona): \App\Entity\Clientes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZona', [$zona]);

        return parent::setZona($zona);
    }

    /**
     * {@inheritDoc}
     */
    public function getDpto(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDpto', []);

        return parent::getDpto();
    }

    /**
     * {@inheritDoc}
     */
    public function setDpto(string $dpto): \App\Entity\Clientes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDpto', [$dpto]);

        return parent::setDpto($dpto);
    }

    /**
     * {@inheritDoc}
     */
    public function getMunicipio(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMunicipio', []);

        return parent::getMunicipio();
    }

    /**
     * {@inheritDoc}
     */
    public function setMunicipio(string $municipio): \App\Entity\Clientes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMunicipio', [$municipio]);

        return parent::setMunicipio($municipio);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefonoMovil(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefonoMovil', []);

        return parent::getTelefonoMovil();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefonoMovil(string $telefonoMovil): \App\Entity\Clientes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefonoMovil', [$telefonoMovil]);

        return parent::setTelefonoMovil($telefonoMovil);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefonoLocal(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefonoLocal', []);

        return parent::getTelefonoLocal();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefonoLocal(string $telefonoLocal): \App\Entity\Clientes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefonoLocal', [$telefonoLocal]);

        return parent::setTelefonoLocal($telefonoLocal);
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccion(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccion', []);

        return parent::getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccion(string $direccion): \App\Entity\Clientes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccion', [$direccion]);

        return parent::setDireccion($direccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFacturas(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFacturas', []);

        return parent::getFacturas();
    }

    /**
     * {@inheritDoc}
     */
    public function addFactura(\App\Entity\Facturas $factura): \App\Entity\Clientes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFactura', [$factura]);

        return parent::addFactura($factura);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFactura(\App\Entity\Facturas $factura): \App\Entity\Clientes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFactura', [$factura]);

        return parent::removeFactura($factura);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
