<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Proveedores extends \App\Entity\Proveedores implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Proveedores' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Proveedores' . "\0" . 'nombreEmpresa', '' . "\0" . 'App\\Entity\\Proveedores' . "\0" . 'contacto', '' . "\0" . 'App\\Entity\\Proveedores' . "\0" . 'telefonoMovil', '' . "\0" . 'App\\Entity\\Proveedores' . "\0" . 'telefonoOfic', '' . "\0" . 'App\\Entity\\Proveedores' . "\0" . 'telefonoParticular', '' . "\0" . 'App\\Entity\\Proveedores' . "\0" . 'ingresos'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Proveedores' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Proveedores' . "\0" . 'nombreEmpresa', '' . "\0" . 'App\\Entity\\Proveedores' . "\0" . 'contacto', '' . "\0" . 'App\\Entity\\Proveedores' . "\0" . 'telefonoMovil', '' . "\0" . 'App\\Entity\\Proveedores' . "\0" . 'telefonoOfic', '' . "\0" . 'App\\Entity\\Proveedores' . "\0" . 'telefonoParticular', '' . "\0" . 'App\\Entity\\Proveedores' . "\0" . 'ingresos'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Proveedores $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreEmpresa(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreEmpresa', []);

        return parent::getNombreEmpresa();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreEmpresa(string $nombreEmpresa): \App\Entity\Proveedores
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreEmpresa', [$nombreEmpresa]);

        return parent::setNombreEmpresa($nombreEmpresa);
    }

    /**
     * {@inheritDoc}
     */
    public function getContacto(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContacto', []);

        return parent::getContacto();
    }

    /**
     * {@inheritDoc}
     */
    public function setContacto(string $contacto): \App\Entity\Proveedores
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContacto', [$contacto]);

        return parent::setContacto($contacto);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefonoMovil(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefonoMovil', []);

        return parent::getTelefonoMovil();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefonoMovil(string $telefonoMovil): \App\Entity\Proveedores
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefonoMovil', [$telefonoMovil]);

        return parent::setTelefonoMovil($telefonoMovil);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefonoOfic(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefonoOfic', []);

        return parent::getTelefonoOfic();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefonoOfic(string $telefonoOfic): \App\Entity\Proveedores
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefonoOfic', [$telefonoOfic]);

        return parent::setTelefonoOfic($telefonoOfic);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefonoParticular(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefonoParticular', []);

        return parent::getTelefonoParticular();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefonoParticular(string $telefonoParticular): \App\Entity\Proveedores
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefonoParticular', [$telefonoParticular]);

        return parent::setTelefonoParticular($telefonoParticular);
    }

    /**
     * {@inheritDoc}
     */
    public function getIngresos(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIngresos', []);

        return parent::getIngresos();
    }

    /**
     * {@inheritDoc}
     */
    public function addIngreso(\App\Entity\Ingresos $ingreso): \App\Entity\Proveedores
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIngreso', [$ingreso]);

        return parent::addIngreso($ingreso);
    }

    /**
     * {@inheritDoc}
     */
    public function removeIngreso(\App\Entity\Ingresos $ingreso): \App\Entity\Proveedores
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIngreso', [$ingreso]);

        return parent::removeIngreso($ingreso);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
