<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Facturas extends \App\Entity\Facturas implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Facturas' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Facturas' . "\0" . 'reciboCaja', '' . "\0" . 'App\\Entity\\Facturas' . "\0" . 'ordenCompra', '' . "\0" . 'App\\Entity\\Facturas' . "\0" . 'fecha', '' . "\0" . 'App\\Entity\\Facturas' . "\0" . 'comentarios', '' . "\0" . 'App\\Entity\\Facturas' . "\0" . 'movimientosdepositos', '' . "\0" . 'App\\Entity\\Facturas' . "\0" . 'idcliente', 'idclientesrelacion', '' . "\0" . 'App\\Entity\\Facturas' . "\0" . 'detallesFacturas', '' . "\0" . 'App\\Entity\\Facturas' . "\0" . 'dias', '' . "\0" . 'App\\Entity\\Facturas' . "\0" . 'forma', '' . "\0" . 'App\\Entity\\Facturas' . "\0" . 'fechavencimiento', '' . "\0" . 'App\\Entity\\Facturas' . "\0" . 'movimientosAlmacens', '' . "\0" . 'App\\Entity\\Facturas' . "\0" . 'numfactura', '' . "\0" . 'App\\Entity\\Facturas' . "\0" . 'serie', '' . "\0" . 'App\\Entity\\Facturas' . "\0" . 'tipofactura'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Facturas' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Facturas' . "\0" . 'reciboCaja', '' . "\0" . 'App\\Entity\\Facturas' . "\0" . 'ordenCompra', '' . "\0" . 'App\\Entity\\Facturas' . "\0" . 'fecha', '' . "\0" . 'App\\Entity\\Facturas' . "\0" . 'comentarios', '' . "\0" . 'App\\Entity\\Facturas' . "\0" . 'movimientosdepositos', '' . "\0" . 'App\\Entity\\Facturas' . "\0" . 'idcliente', 'idclientesrelacion', '' . "\0" . 'App\\Entity\\Facturas' . "\0" . 'detallesFacturas', '' . "\0" . 'App\\Entity\\Facturas' . "\0" . 'dias', '' . "\0" . 'App\\Entity\\Facturas' . "\0" . 'forma', '' . "\0" . 'App\\Entity\\Facturas' . "\0" . 'fechavencimiento', '' . "\0" . 'App\\Entity\\Facturas' . "\0" . 'movimientosAlmacens', '' . "\0" . 'App\\Entity\\Facturas' . "\0" . 'numfactura', '' . "\0" . 'App\\Entity\\Facturas' . "\0" . 'serie', '' . "\0" . 'App\\Entity\\Facturas' . "\0" . 'tipofactura'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Facturas $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getReciboCaja(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReciboCaja', []);

        return parent::getReciboCaja();
    }

    /**
     * {@inheritDoc}
     */
    public function setReciboCaja(string $reciboCaja): \App\Entity\Facturas
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReciboCaja', [$reciboCaja]);

        return parent::setReciboCaja($reciboCaja);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrdenCompra(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrdenCompra', []);

        return parent::getOrdenCompra();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrdenCompra(string $ordenCompra): \App\Entity\Facturas
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrdenCompra', [$ordenCompra]);

        return parent::setOrdenCompra($ordenCompra);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', []);

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha(\DateTimeInterface $fecha): \App\Entity\Facturas
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', [$fecha]);

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getComentarios(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComentarios', []);

        return parent::getComentarios();
    }

    /**
     * {@inheritDoc}
     */
    public function setComentarios(string $comentarios): \App\Entity\Facturas
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComentarios', [$comentarios]);

        return parent::setComentarios($comentarios);
    }

    /**
     * {@inheritDoc}
     */
    public function getMovimientosdepositos(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMovimientosdepositos', []);

        return parent::getMovimientosdepositos();
    }

    /**
     * {@inheritDoc}
     */
    public function addMovimientosdeposito(\App\Entity\MovimientosDepositos $movimientosdeposito): \App\Entity\Facturas
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMovimientosdeposito', [$movimientosdeposito]);

        return parent::addMovimientosdeposito($movimientosdeposito);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMovimientosdeposito(\App\Entity\MovimientosDepositos $movimientosdeposito): \App\Entity\Facturas
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMovimientosdeposito', [$movimientosdeposito]);

        return parent::removeMovimientosdeposito($movimientosdeposito);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdcliente(): ?\App\Entity\Clientes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdcliente', []);

        return parent::getIdcliente();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdcliente(?\App\Entity\Clientes $idcliente): \App\Entity\Facturas
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdcliente', [$idcliente]);

        return parent::setIdcliente($idcliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdclientesrelacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdclientesrelacion', []);

        return parent::getIdclientesrelacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdclientesrelacion($idclientesrelacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdclientesrelacion', [$idclientesrelacion]);

        return parent::setIdclientesrelacion($idclientesrelacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDetallesFacturas(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDetallesFacturas', []);

        return parent::getDetallesFacturas();
    }

    /**
     * {@inheritDoc}
     */
    public function addDetallesFactura(\App\Entity\DetallesFactura $detallesFactura): \App\Entity\Facturas
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDetallesFactura', [$detallesFactura]);

        return parent::addDetallesFactura($detallesFactura);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDetallesFactura(\App\Entity\DetallesFactura $detallesFactura): \App\Entity\Facturas
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDetallesFactura', [$detallesFactura]);

        return parent::removeDetallesFactura($detallesFactura);
    }

    /**
     * {@inheritDoc}
     */
    public function getDias(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDias', []);

        return parent::getDias();
    }

    /**
     * {@inheritDoc}
     */
    public function setDias(int $dias): \App\Entity\Facturas
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDias', [$dias]);

        return parent::setDias($dias);
    }

    /**
     * {@inheritDoc}
     */
    public function getForma(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getForma', []);

        return parent::getForma();
    }

    /**
     * {@inheritDoc}
     */
    public function setForma(string $forma): \App\Entity\Facturas
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setForma', [$forma]);

        return parent::setForma($forma);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechavencimiento(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechavencimiento', []);

        return parent::getFechavencimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechavencimiento(\DateTimeInterface $fechavencimiento): \App\Entity\Facturas
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechavencimiento', [$fechavencimiento]);

        return parent::setFechavencimiento($fechavencimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getMovimientosAlmacens(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMovimientosAlmacens', []);

        return parent::getMovimientosAlmacens();
    }

    /**
     * {@inheritDoc}
     */
    public function addMovimientosAlmacen(\App\Entity\MovimientosAlmacen $movimientosAlmacen): \App\Entity\Facturas
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMovimientosAlmacen', [$movimientosAlmacen]);

        return parent::addMovimientosAlmacen($movimientosAlmacen);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMovimientosAlmacen(\App\Entity\MovimientosAlmacen $movimientosAlmacen): \App\Entity\Facturas
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMovimientosAlmacen', [$movimientosAlmacen]);

        return parent::removeMovimientosAlmacen($movimientosAlmacen);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumfactura(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumfactura', []);

        return parent::getNumfactura();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumfactura(string $numfactura): \App\Entity\Facturas
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumfactura', [$numfactura]);

        return parent::setNumfactura($numfactura);
    }

    /**
     * {@inheritDoc}
     */
    public function getSerie(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSerie', []);

        return parent::getSerie();
    }

    /**
     * {@inheritDoc}
     */
    public function setSerie(string $serie): \App\Entity\Facturas
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSerie', [$serie]);

        return parent::setSerie($serie);
    }

    /**
     * {@inheritDoc}
     */
    public function getCantidadactual(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCantidadactual', []);

        return parent::getCantidadactual();
    }

    /**
     * {@inheritDoc}
     */
    public function setCantidadactual(int $cantidadactual): \App\Entity\Facturas
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCantidadactual', [$cantidadactual]);

        return parent::setCantidadactual($cantidadactual);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipofactura(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipofactura', []);

        return parent::getTipofactura();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipofactura(string $tipofactura): \App\Entity\Facturas
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipofactura', [$tipofactura]);

        return parent::setTipofactura($tipofactura);
    }

}
