<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ug26py1' shared service.

return $this->privates['.service_locator.ug26py1'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('proveedore' => function (): \App\Entity\Proveedores {
    return ($this->privates['.errored..service_locator.ug26py1.App\Entity\Proveedores'] ?? $this->load('getProveedoresService.php'));
}));
