<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.GhCUbNg' shared service.

return $this->privates['.service_locator.GhCUbNg'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('almacen' => function (): \App\Entity\Almacen {
    return ($this->privates['.errored..service_locator.GhCUbNg.App\Entity\Almacen'] ?? $this->load('getAlmacenService.php'));
}));
