<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.9Dq1.6i' shared service.

return $this->privates['.service_locator.9Dq1.6i'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('ingreso' => function (): \App\Entity\Ingresos {
    return ($this->privates['.errored..service_locator.9Dq1.6i.App\Entity\Ingresos'] ?? $this->load('getIngresosService.php'));
}));
