<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.kFI1I3_' shared service.

return $this->privates['.service_locator.kFI1I3_'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('detallesFacturaRepository' => function (): \App\Repository\DetallesFacturaRepository {
    return ($this->privates['App\Repository\DetallesFacturaRepository'] ?? $this->load('getDetallesFacturaRepositoryService.php'));
}));
