<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.6BMcKXC' shared service.

return $this->privates['.service_locator.6BMcKXC'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('movimientosDepositosRepository' => function (): \App\Repository\MovimientosDepositosRepository {
    return ($this->privates['App\Repository\MovimientosDepositosRepository'] ?? $this->load('getMovimientosDepositosRepositoryService.php'));
}));
