<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.0fqA5K5' shared service.

return $this->privates['.service_locator.0fqA5K5'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('detallesFactura' => function (): \App\Entity\DetallesFactura {
    return ($this->privates['.errored..service_locator.0fqA5K5.App\Entity\DetallesFactura'] ?? $this->load('getDetallesFacturaService.php'));
}));
