<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ohh9a7M' shared service.

return $this->privates['.service_locator.ohh9a7M'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('clientesRepository' => function (): \App\Repository\ClientesRepository {
    return ($this->privates['App\Repository\ClientesRepository'] ?? $this->load('getClientesRepositoryService.php'));
}));
