<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'pugx_autocompleter.filter.doctrine_subscriber' shared service.

include_once $this->targetDirs[3].'/vendor/pugx/autocompleter-bundle/src/Listener/FilterSubscriber.php';

return $this->services['pugx_autocompleter.filter.doctrine_subscriber'] = new \PUGX\AutocompleterBundle\Listener\FilterSubscriber();
