<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'console.command.form_debug' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\console\\Command\\Command.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\Command\\DebugCommand.php';

$this->privates['console.command.form_debug'] = $instance = new \Symfony\Component\Form\Command\DebugCommand(($this->privates['form.registry'] ?? $this->load('getForm_RegistryService.php')), array(0 => 'Symfony\\Component\\Form\\Extension\\Core\\Type', 1 => 'App\\Form', 2 => 'Symfony\\Bridge\\Doctrine\\Form\\Type', 3 => 'FOS\\CKEditorBundle\\Form\\Type', 4 => ''), array(0 => 'App\\Form\\AlmacenType', 1 => 'App\\Form\\ClientesType', 2 => 'App\\Form\\ContratarType', 3 => 'App\\Form\\DetallesFacturaType', 4 => 'App\\Form\\FacturasType', 5 => 'App\\Form\\FamiliaType', 6 => 'App\\Form\\MovimientosAlmacenType', 7 => 'App\\Form\\MovimientosDepositos1Type', 8 => 'App\\Form\\MovimientosDepositosType', 9 => 'App\\Form\\ProductosType', 10 => 'App\\Form\\ProveedoresType', 11 => 'App\\Form\\UserType', 12 => 'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType', 13 => 'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType', 14 => 'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType', 15 => 'FOS\\CKEditorBundle\\Form\\Type\\CKEditorType', 16 => 'PUGX\\AutocompleterBundle\\Form\\Type\\AutocompleteType', 17 => 'PUGX\\AutocompleterBundle\\Form\\Type\\AutocompleteFilterType'), array(0 => 'Symfony\\Component\\Form\\Extension\\HttpFoundation\\Type\\FormTypeHttpFoundationExtension', 1 => 'Symfony\\Component\\Form\\Extension\\Validator\\Type\\FormTypeValidatorExtension', 2 => 'Symfony\\Component\\Form\\Extension\\Validator\\Type\\RepeatedTypeValidatorExtension', 3 => 'Symfony\\Component\\Form\\Extension\\Validator\\Type\\SubmitTypeValidatorExtension', 4 => 'Symfony\\Component\\Form\\Extension\\Validator\\Type\\UploadValidatorExtension', 5 => 'Symfony\\Component\\Form\\Extension\\Csrf\\Type\\FormTypeCsrfExtension', 6 => 'Symfony\\Component\\Form\\Extension\\DataCollector\\Type\\DataCollectorTypeExtension'), array(0 => 'Symfony\\Component\\Form\\Extension\\Validator\\ValidatorTypeGuesser', 1 => 'Symfony\\Bridge\\Doctrine\\Form\\DoctrineOrmTypeGuesser'));

$instance->setName('debug:form');

return $instance;
