<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.wTK5wS5' shared service.

return $this->privates['.service_locator.wTK5wS5'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('movimientosDeposito' => function (): \App\Entity\MovimientosDepositos {
    return ($this->privates['.errored..service_locator.wTK5wS5.App\Entity\MovimientosDepositos'] ?? $this->load('getMovimientosDepositos2Service.php'));
}));
