<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.A4AyGBH' shared service.

return $this->privates['.service_locator.A4AyGBH'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('movimientosAlmacen' => function (): \App\Entity\MovimientosAlmacen {
    return ($this->privates['.errored..service_locator.A4AyGBH.App\Entity\MovimientosAlmacen'] ?? $this->load('getMovimientosAlmacenService.php'));
}));
