<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.YU.8.TJ' shared service.

return $this->privates['.service_locator.YU.8.TJ'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('factura' => function (): \App\Entity\Facturas {
    return ($this->privates['.errored..service_locator.YU.8.TJ.App\Entity\Facturas'] ?? $this->load('getFacturas2Service.php'));
}));
