<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.MpabvJx' shared service.

return $this->privates['.service_locator.MpabvJx'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('producto' => function (): \App\Entity\Productos {
    return ($this->privates['.errored..service_locator.MpabvJx.App\Entity\Productos'] ?? $this->load('getProductosService.php'));
}));
