<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.oTyE6Eq' shared service.

return $this->privates['.service_locator.oTyE6Eq'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('familiaRepository' => function (): \App\Repository\FamiliaRepository {
    return ($this->privates['App\Repository\FamiliaRepository'] ?? $this->load('getFamiliaRepositoryService.php'));
}));
