<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.wTK5wS5.App\Entity\MovimientosDepositos' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.wTK5wS5": it references class "App\\Entity\\MovimientosDepositos" but no such service exists.');
