<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGxPRNy5\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGxPRNy5/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerGxPRNy5.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerGxPRNy5\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerGxPRNy5\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'GxPRNy5',
    'container.build_id' => '10556636',
    'container.build_time' => 1540092258,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerGxPRNy5');
