<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQdoDZKj\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQdoDZKj/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQdoDZKj.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQdoDZKj\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerQdoDZKj\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'QdoDZKj',
    'container.build_id' => '67802116',
    'container.build_time' => 1540317410,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerQdoDZKj');
