<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDj64lSR\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDj64lSR/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerDj64lSR.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerDj64lSR\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerDj64lSR\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Dj64lSR',
    'container.build_id' => '5a295589',
    'container.build_time' => 1543187753,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerDj64lSR');
