<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.fAmOCKw' shared service.

return $this->privates['.service_locator.fAmOCKw'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('facturasRepository' => function (): \App\Repository\FacturasRepository {
    return ($this->privates['App\Repository\FacturasRepository'] ?? $this->load('getFacturasRepositoryService.php'));
}));
