<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DetallesFactura extends \App\Entity\DetallesFactura implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\DetallesFactura' . "\0" . 'id', '' . "\0" . 'App\\Entity\\DetallesFactura' . "\0" . 'idproducto', '' . "\0" . 'App\\Entity\\DetallesFactura' . "\0" . 'idfactura', '' . "\0" . 'App\\Entity\\DetallesFactura' . "\0" . 'cantidad', '' . "\0" . 'App\\Entity\\DetallesFactura' . "\0" . 'ordenPromocion', '' . "\0" . 'App\\Entity\\DetallesFactura' . "\0" . 'comentarios', '' . "\0" . 'App\\Entity\\DetallesFactura' . "\0" . 'precio', '' . "\0" . 'App\\Entity\\DetallesFactura' . "\0" . 'total', '' . "\0" . 'App\\Entity\\DetallesFactura' . "\0" . 'descuento'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\DetallesFactura' . "\0" . 'id', '' . "\0" . 'App\\Entity\\DetallesFactura' . "\0" . 'idproducto', '' . "\0" . 'App\\Entity\\DetallesFactura' . "\0" . 'idfactura', '' . "\0" . 'App\\Entity\\DetallesFactura' . "\0" . 'cantidad', '' . "\0" . 'App\\Entity\\DetallesFactura' . "\0" . 'ordenPromocion', '' . "\0" . 'App\\Entity\\DetallesFactura' . "\0" . 'comentarios', '' . "\0" . 'App\\Entity\\DetallesFactura' . "\0" . 'precio', '' . "\0" . 'App\\Entity\\DetallesFactura' . "\0" . 'total', '' . "\0" . 'App\\Entity\\DetallesFactura' . "\0" . 'descuento'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (DetallesFactura $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdproducto(): ?\App\Entity\Productos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdproducto', []);

        return parent::getIdproducto();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdproducto(?\App\Entity\Productos $idproducto): \App\Entity\DetallesFactura
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdproducto', [$idproducto]);

        return parent::setIdproducto($idproducto);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdfactura(): ?\App\Entity\Facturas
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdfactura', []);

        return parent::getIdfactura();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdfactura(?\App\Entity\Facturas $idfactura): \App\Entity\DetallesFactura
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdfactura', [$idfactura]);

        return parent::setIdfactura($idfactura);
    }

    /**
     * {@inheritDoc}
     */
    public function getCantidad(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCantidad', []);

        return parent::getCantidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setCantidad(int $cantidad): \App\Entity\DetallesFactura
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCantidad', [$cantidad]);

        return parent::setCantidad($cantidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrdenPromocion(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrdenPromocion', []);

        return parent::getOrdenPromocion();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrdenPromocion(string $ordenPromocion): \App\Entity\DetallesFactura
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrdenPromocion', [$ordenPromocion]);

        return parent::setOrdenPromocion($ordenPromocion);
    }

    /**
     * {@inheritDoc}
     */
    public function getComentarios(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComentarios', []);

        return parent::getComentarios();
    }

    /**
     * {@inheritDoc}
     */
    public function setComentarios(string $comentarios): \App\Entity\DetallesFactura
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComentarios', [$comentarios]);

        return parent::setComentarios($comentarios);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrecio(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrecio', []);

        return parent::getPrecio();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrecio(float $precio): \App\Entity\DetallesFactura
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrecio', [$precio]);

        return parent::setPrecio($precio);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotal(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotal', []);

        return parent::getTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotal(float $total): \App\Entity\DetallesFactura
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotal', [$total]);

        return parent::setTotal($total);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescuento(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescuento', []);

        return parent::getDescuento();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescuento(?float $descuento): \App\Entity\DetallesFactura
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescuento', [$descuento]);

        return parent::setDescuento($descuento);
    }

}
