<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Ingresos extends \App\Entity\Ingresos implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Ingresos' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Ingresos' . "\0" . 'productos', '' . "\0" . 'App\\Entity\\Ingresos' . "\0" . 'proveedor', '' . "\0" . 'App\\Entity\\Ingresos' . "\0" . 'Almacen', '' . "\0" . 'App\\Entity\\Ingresos' . "\0" . 'cantidad', '' . "\0" . 'App\\Entity\\Ingresos' . "\0" . 'fecha', '' . "\0" . 'App\\Entity\\Ingresos' . "\0" . 'comentario', '' . "\0" . 'App\\Entity\\Ingresos' . "\0" . 'vencimiento'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Ingresos' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Ingresos' . "\0" . 'productos', '' . "\0" . 'App\\Entity\\Ingresos' . "\0" . 'proveedor', '' . "\0" . 'App\\Entity\\Ingresos' . "\0" . 'Almacen', '' . "\0" . 'App\\Entity\\Ingresos' . "\0" . 'cantidad', '' . "\0" . 'App\\Entity\\Ingresos' . "\0" . 'fecha', '' . "\0" . 'App\\Entity\\Ingresos' . "\0" . 'comentario', '' . "\0" . 'App\\Entity\\Ingresos' . "\0" . 'vencimiento'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Ingresos $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getProductos(): ?\App\Entity\Productos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductos', []);

        return parent::getProductos();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductos(?\App\Entity\Productos $productos): \App\Entity\Ingresos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductos', [$productos]);

        return parent::setProductos($productos);
    }

    /**
     * {@inheritDoc}
     */
    public function getProveedor(): ?\App\Entity\Proveedores
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProveedor', []);

        return parent::getProveedor();
    }

    /**
     * {@inheritDoc}
     */
    public function setProveedor(?\App\Entity\Proveedores $proveedor): \App\Entity\Ingresos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProveedor', [$proveedor]);

        return parent::setProveedor($proveedor);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlmacen(): ?\App\Entity\Almacen
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlmacen', []);

        return parent::getAlmacen();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlmacen(?\App\Entity\Almacen $Almacen): \App\Entity\Ingresos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlmacen', [$Almacen]);

        return parent::setAlmacen($Almacen);
    }

    /**
     * {@inheritDoc}
     */
    public function getCantidad(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCantidad', []);

        return parent::getCantidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setCantidad(int $cantidad): \App\Entity\Ingresos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCantidad', [$cantidad]);

        return parent::setCantidad($cantidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', []);

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha(\DateTimeInterface $fecha): \App\Entity\Ingresos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', [$fecha]);

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getComentario(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComentario', []);

        return parent::getComentario();
    }

    /**
     * {@inheritDoc}
     */
    public function setComentario(string $comentario): \App\Entity\Ingresos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComentario', [$comentario]);

        return parent::setComentario($comentario);
    }

    /**
     * {@inheritDoc}
     */
    public function getVencimiento(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVencimiento', []);

        return parent::getVencimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setVencimiento(\DateTimeInterface $vencimiento): \App\Entity\Ingresos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVencimiento', [$vencimiento]);

        return parent::setVencimiento($vencimiento);
    }

}
