<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MovimientosAlmacen extends \App\Entity\MovimientosAlmacen implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\MovimientosAlmacen' . "\0" . 'id', '' . "\0" . 'App\\Entity\\MovimientosAlmacen' . "\0" . 'IdProducto', '' . "\0" . 'App\\Entity\\MovimientosAlmacen' . "\0" . 'Destino', '' . "\0" . 'App\\Entity\\MovimientosAlmacen' . "\0" . 'Origen', '' . "\0" . 'App\\Entity\\MovimientosAlmacen' . "\0" . 'Cantidad', '' . "\0" . 'App\\Entity\\MovimientosAlmacen' . "\0" . 'Status', '' . "\0" . 'App\\Entity\\MovimientosAlmacen' . "\0" . 'IdCliente', '' . "\0" . 'App\\Entity\\MovimientosAlmacen' . "\0" . 'Fecha', '' . "\0" . 'App\\Entity\\MovimientosAlmacen' . "\0" . 'Comentarios', '' . "\0" . 'App\\Entity\\MovimientosAlmacen' . "\0" . 'idfactura', 'desde', 'hasta'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\MovimientosAlmacen' . "\0" . 'id', '' . "\0" . 'App\\Entity\\MovimientosAlmacen' . "\0" . 'IdProducto', '' . "\0" . 'App\\Entity\\MovimientosAlmacen' . "\0" . 'Destino', '' . "\0" . 'App\\Entity\\MovimientosAlmacen' . "\0" . 'Origen', '' . "\0" . 'App\\Entity\\MovimientosAlmacen' . "\0" . 'Cantidad', '' . "\0" . 'App\\Entity\\MovimientosAlmacen' . "\0" . 'Status', '' . "\0" . 'App\\Entity\\MovimientosAlmacen' . "\0" . 'IdCliente', '' . "\0" . 'App\\Entity\\MovimientosAlmacen' . "\0" . 'Fecha', '' . "\0" . 'App\\Entity\\MovimientosAlmacen' . "\0" . 'Comentarios', '' . "\0" . 'App\\Entity\\MovimientosAlmacen' . "\0" . 'idfactura', 'desde', 'hasta'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (MovimientosAlmacen $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdProducto(): ?\App\Entity\Productos
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdProducto', []);

        return parent::getIdProducto();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdProducto(?\App\Entity\Productos $IdProducto): \App\Entity\MovimientosAlmacen
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdProducto', [$IdProducto]);

        return parent::setIdProducto($IdProducto);
    }

    /**
     * {@inheritDoc}
     */
    public function getDestino(): ?\App\Entity\Almacen
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDestino', []);

        return parent::getDestino();
    }

    /**
     * {@inheritDoc}
     */
    public function setDestino(?\App\Entity\Almacen $Destino): \App\Entity\MovimientosAlmacen
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDestino', [$Destino]);

        return parent::setDestino($Destino);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrigen(): ?\App\Entity\Almacen
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrigen', []);

        return parent::getOrigen();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrigen(?\App\Entity\Almacen $Origen): \App\Entity\MovimientosAlmacen
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrigen', [$Origen]);

        return parent::setOrigen($Origen);
    }

    /**
     * {@inheritDoc}
     */
    public function getCantidad(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCantidad', []);

        return parent::getCantidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setCantidad(int $Cantidad): \App\Entity\MovimientosAlmacen
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCantidad', [$Cantidad]);

        return parent::setCantidad($Cantidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(?int $Status): \App\Entity\MovimientosAlmacen
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$Status]);

        return parent::setStatus($Status);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCliente(): ?\App\Entity\Clientes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCliente', []);

        return parent::getIdCliente();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCliente(?\App\Entity\Clientes $IdCliente): \App\Entity\MovimientosAlmacen
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCliente', [$IdCliente]);

        return parent::setIdCliente($IdCliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', []);

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha(\DateTimeInterface $Fecha): \App\Entity\MovimientosAlmacen
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', [$Fecha]);

        return parent::setFecha($Fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getComentarios(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComentarios', []);

        return parent::getComentarios();
    }

    /**
     * {@inheritDoc}
     */
    public function setComentarios(?string $Comentarios): \App\Entity\MovimientosAlmacen
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComentarios', [$Comentarios]);

        return parent::setComentarios($Comentarios);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdfactura(): ?\App\Entity\Facturas
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdfactura', []);

        return parent::getIdfactura();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdfactura(?\App\Entity\Facturas $idfactura): \App\Entity\MovimientosAlmacen
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdfactura', [$idfactura]);

        return parent::setIdfactura($idfactura);
    }

    /**
     * {@inheritDoc}
     */
    public function getDesde()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDesde', []);

        return parent::getDesde();
    }

    /**
     * {@inheritDoc}
     */
    public function setDesde($desde)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDesde', [$desde]);

        return parent::setDesde($desde);
    }

    /**
     * {@inheritDoc}
     */
    public function getHasta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHasta', []);

        return parent::getHasta();
    }

    /**
     * {@inheritDoc}
     */
    public function setHasta($hasta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHasta', [$hasta]);

        return parent::setHasta($hasta);
    }

}
